# Generated by Django 5.0.1 on 2024-02-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('term', models.TextField(max_length=20)),
                ('finish_by', models.DateTimeField()),
                ('is_completed', models.BooleanField()),
            ],
        ),
    ]
